// check auth events
export const CHECK_JWT_USER = "CHECK_JWT_USER";
export const CHECK_JWT_USER_LOAD = "CHECK_JWT_USER_LOAD";
export const CHECK_JWT_USER_FAIL = "CHECK_JWT_USER_FAIL";
export const CHECK_JWT_USER_DATA = "CHECK_JWT_USER_DATA";

// auth
export const AUTH_TRUSY = "AUTH_LOGIN";
export const AUTH_JWT = "AUTH_JWT";
export const AUTH_USER = "AUTH_USER";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL";
export const AUTH_LOGOUT_LOAD = "AUTH_LOGOUT_LOAD";

// entites count
export const ENTITIES_COUNT_LOAD = "ENTITIES_COUNT_LOAD";
export const ENTITIES_COUNT_FAIL = "ENTITIES_COUNT_FAIL";
export const ENTITIES_COUNT_DATA = "ENTITIES_COUNT_DATA";
export const ENTITIES_COUNT = "ENTITIES_COUNT";

//  profile page

export const UPDATE_PROFILE_UPDATED_DATA = "UPDATE_PROFILE_UPDATED_DATA"; // FORM DATA
export const UPDATE_PROFILE_LOAD = "UPDATE_PROFILE_LOAD";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_SAVED_DATA = "UPDATE_PROFILE_SAVED_DATA";
export const UPDATE_PROFILE_PASSWORD = "UPDATE_PROFILE_PASSWORD";

// CONFIRMATION

export const CONFIRMATION_PROCESS_LOAD = "CONFIRMATION_PROCESS_LOAD";
export const CONFIRMATION_PROCESS_FAIL = "CONFIRMATION_PROCESS_FAIL";
export const CONFIRMATION_PROCESS_STATUS = "CONFIRMATION_PROCESS_STATUS";
